name: deploy
on:
  push:
    branches:
    - main
permissions:
  contents: write
jobs:
  deploy:
    # Recommended if you make multiple deployments in quick succession.
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Load Yarn Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/yarn
          key: deploy-${{ runner.os }}-yarn-v0-${{ hashFiles('yarn.lock') }}

      - name: Build
        run: ci/build.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
